name: "protolint"

on:
  push:
    branches: "*"

jobs:
  proto-lint:
    runs-on: ubuntu-latest
    name: "Buf: Lint"
    steps:
      # 1: Pull code.
      - uses: actions/checkout@v2

      # 2: Setup Buf.
      - uses: bufbuild/buf-setup-action@v0.1.0
        with:
          version: '0.41.0'

      # 3: Run linter.
      - uses: bufbuild/buf-lint-action@v0.2.0
        with:
          github_token: ${{ github.token }}

