name: "copybara"

on:
  push:
    branches:
      - master
      - release/*
      - site/*

blocks:
  copybara-check: &check
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
  copybara-migrate: &migrate
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
  cookiebot: &cookiebot
    git_name: Cookiebot
    git_email: techteam+github@cookiescalifornia.com
    git_credentials: ${{ secrets.BOT_API_CREDS }}
    ssh_key: ${{ secrets.BOT_SSH_KEY }}
    ssh_known_hosts: ${{ secrets.BOT_KNOWN_HOSTS }}
    gpg_key: ${{ secrets.BOT_GPG_KEY }}
    gpg_key_id: ${{ secrets.BOT_GPG_KEY_ID }}
    image: us.gcr.io/elide-ai/tools/copybara:latest

jobs:
  copybara-validate-site: *check
    name: "Validate: Site"
    steps:
      # 1: Pull code.
      - uses: actions/checkout@v2

      # 2: Validate migration via Copybara.
      - name: Validate Migration
        uses: &image sgammon/copybara-action@6c67a935b499c976bc597bb24dd5143ea2082b02
        with: *cookiebot
          workflow: site
          command: validate

  copybara-validate-protocol: *check
    name: "Validate: Protocol"
    steps:
      # 1: Pull code.
      - uses: actions/checkout@v2

      # 2: Validate migration via Copybara.
      - name: Validate Migration
        uses: *image
        with: *cookiebot
          workflow: site
          command: validate

  copybara-migrate-site: *migrate
    name: "Sync: Site"
    steps:
      # 1: Pull code.
      - uses: actions/checkout@v2

      # 2: Validate migration via Copybara.
      - name: Validate Migration
        uses: *image
        with: *cookiebot
          workflow: site
          command: validate

      # 3: Publish to site as PR.
      - name: Migration
        uses: *image
        with: *cookiebot
          workflow: site
          command: migrate

  copybara-migrate-protocol: *migrate
    name: "Sync: Site"
    steps:
      # 1: Pull code.
      - uses: actions/checkout@v2

      # 2: Validate migration via Copybara.
      - name: Validate Migration
        uses: *image
        with: *cookiebot
          workflow: protocol
          command: validate

      # 3: Publish to protocol as PR.
      - name: Migration
        uses: *image
        with: *cookiebot
          workflow: site
          command: migrate
